### PR TITLE
Issue 142 - Allow users to provide a botocore session on creation of S3FileSystem

### PR DESCRIPTION
**Pull request by mfulleratlassian**
See: https://github.com/dask/s3fs/issues/142

### CODE REVIEW

**Comment by martindurant** [comment]
A very reasonable request. Perhaps I would remove the code duplication by having 
```
if self.passed_in_session:
    ..
elif self.anon:
```

Can this be tested? The simplest would be to create a new instance, passing a session, and ensure that the `session` attribute is indeed the session we passed.

Have you thoughts on what should happen in the case of pickling?

**Comment by mfulleratlassian** [comment]
Yeah I was just looking at the pickling code now. I will simplify the duplication and see what can be done with pickling. At the least I can make it raise a NotImplemented if you pass in a session.

**Comment by martindurant** [comment]
> I can make it raise a NotImplemented if you pass in a session

that is probably suitable. Wouldn't mind  a test for that too :)

**Comment by mfulleratlassian** [comment]
OK I have added some tests, prevented Pickling with a passed in session and tried to clean up the code. Let me know what else you would like updated. Thanks

**Comment by mfulleratlassian** [comment]
Sweet, any ideas when you are planning the next release to PyPi? Once this goes out we can remove the custom version from our repos. 😃

**Comment by martindurant** [comment]
There was no release since the end of April, so I suppose it could - I'll try to fit it in in the near future.

**Comment by mfulleratlassian** [comment]
Thanks

**Pull request merged**
