### PR TITLE
Append wretry merge

### PR DESCRIPTION
**Pull request by martindurant**
Adds retries on write: raises after 10 tries by default. Recommend to catch that, and truncate at that point (self f.buffer to empty io.BytestIO, and call close()), could be done automatically.

Marge does multi-part copying on the server side, to allow splitting of big file and parallel upload.

Append mode either makes first chunk be the existing file (if size>=5MB) or downloads existing data if small. This means that the original file will *briefly* not exist.

### CODE REVIEW

**Comment by jcrist** [comment]
Looks like this is on top of #19 (not sure if intended). Overall this looks great to me. It might be nice to optionally apply the spit and merge operations in a fluid interface when writing (perhaps `s3.write(data, multipart=True)`), but that could come later if needed.

**Comment by martindurant** [comment]
What would you expect `multipart=True` to do? 

At the moment, data is uploaded whenever the latest write took the internal buffer over the block+size (minimum 5MB, default 5MB).

**Comment by jcrist** [comment]
Not sure. In a more general sense I was wondering if there may be a way to succinctly spell "take this large chunk of bytes and upload it in parts, then merge on the server".  This may be out of scope for s3fs though.

**Comment by martindurant** [comment]
I think that belongs in `distributed.s3`. From a single thread, I don't see much advantage - uploads are already chunks merged on the server. 

I suppose if the S3File were pickleable, a write process could be restarted sometime later. It appears to be pickleable as is, I haven't checked yet whether that's enough.

**Comment by mrocklin** [comment]
Generally this looks fine to me.

**Pull request merged**
