### PR TITLE
Compatibility for fsspec

### PR DESCRIPTION
**Pull request by martindurant**
(much removed code!)

Many path/directory-specific things fail.
Text mode no longer supported directly in the class.
Mapper no longer required at all (tests can be adapted).

### CODE REVIEW

**Comment by dvukolov** [comment]
Martin, could you please add fsspec to requirements.txt?

**Comment by martindurant** [comment]
Yes, will do. First, I need to get moto working, then fix the tests... This is just an experiment for now, and s3fs based on fsspec will not be released for quite some time.

**Comment by martindurant** [comment]
cc @TomAugspurger ; this is pretty close to done.

**Comment by TomAugspurger** [comment]
👍 looks nice on a quick glance. Do you plan to update `setup.py` to include fsspec in a future PR? Also is this PR dropping py27 support? May want to include a `python_requires` in the setup.py if that's the case.

**Comment by martindurant** [comment]
Yes it will, both those things - but it's still WIP for now. Nice to see that there is a lot of red in the changes.

**Comment by martindurant** [comment]
@mariusvniekerk , would appreciate if you could subject this to heavy testing

**Pull request merged**
