### PR TITLE
Add copy_managed to use the managed copy functions in boto3

### PR DESCRIPTION
**Pull request by mariusvniekerk**
These are required if an object exceeds 5GB in size.

### CODE REVIEW

**Comment by martindurant** [comment]
What's the real difference here? It looks like `CopySource='/'.join([buc1, key1])` versus `CopySource={'Bucket': buc1,'Key': key1}`, and calling `s3.copy` instead of `s3.copy_object`.

Why the move for the boto3 install? Suggests the library won't work with the conda boto3?

**Comment by mariusvniekerk** [comment]
Mostly just fiddling with getting CI passing.  The conda boto3 is pretty heavily out of date.

**Comment by martindurant** [comment]
Perhaps specify conda-forge? Looks pretty up to date on there https://anaconda.org/conda-forge/boto3/files

**Comment by mariusvniekerk** [comment]
The key different is copy vs copy_object.   Copy is a higher order boto3 method that uses s3transfer under the hood allowing things like callbacks etc.  Ultimately it uses uploadPartCopy instead of copyObject.

**Comment by mariusvniekerk** [comment]
I'm not sure if those are supported by other s3 compatible engines though.

**Comment by martindurant** [comment]
@mariusvniekerk , if this ready for merger?

**Comment by mariusvniekerk** [comment]
Yep. The rest of the apis we use in s3fs are safe with large files

**Comment by kinzleb** [comment]
This is working great for me, really improved copy times for large files -- thanks!

**Comment by martindurant** [comment]
Glad it helped. This was released today in v0.1.4 on conda-forge and pypi.

**Pull request merged**
