### PR TITLE
More logging, and set with env var

### PR DESCRIPTION
**Pull request by martindurant**
cc @birdsarah @TomAugspurger

### CODE REVIEW

**Comment by martindurant** [comment]
@birdsarah, this will give you more logging, and you can turn it on with an environment variable, rather than having to run any Dask commands.

**Comment by birdsarah** [comment]
how do you set an environment variable on a worker?

**Comment by martindurant** [comment]
> how do you set an environment variable on a worker?

This is the *easy* way, set it for the whole system, in whatever way you normally set environment variables. I am assuming you control other things this way.

**Comment by birdsarah** [comment]
?? I'm confused. I spin up workers using DaskYarn. I'm not understanding you at all.

**Comment by martindurant** [comment]
I believe dask-yarn allows you to pass on an environment ( @jcrist )

**Comment by martindurant** [comment]
Specifically, there is the `env: {}` tag in https://yarn.dask.org/en/latest/configuration.html#default-configuration , which applies to each of your container types. So you would make a configuration with 
```yaml
  worker:
    env:
       S3FS_LOGGING_LEVEL: DEBUG
```
(this can also be set via the [programmatic API](https://yarn.dask.org/en/latest/api.html#dask_yarn.YarnCluster), `worker_env=` )

**Comment by birdsarah** [comment]
I'm installing s3fs from master to use this, but I can't seem to run this with dask.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-64a3ac533778> in <module>
     10         path,
     11         engine='fastparquet',
---> 12         gather_statistics=False,
     13     )
     14 

/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, **kwargs)
    135     if hasattr(path, "name"):
    136         path = stringify_path(path)
--> 137     fs, _, paths = get_fs_token_paths(path, mode="rb", storage_options=storage_options)
    138 
    139     paths = sorted(paths, key=natural_sort_key)  # numeric rather than glob ordering

/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/fsspec/core.py in get_fs_token_paths(urlpath, mode, num, name_function, storage_options, protocol)
    311         protocols, path = split_protocol(urlpath)
    312         protocol = protocol or protocols
--> 313         cls = get_filesystem_class(protocol)
    314 
    315         options = cls._get_kwargs_from_urls(urlpath)

/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/fsspec/registry.py in get_filesystem_class(protocol)
     78         if minversion:
     79             version = getattr(mod, "__version__", None)
---> 80             if version and LooseVersion(version) < minversion:
     81                 raise RuntimeError("'{}={}' is installed, but version '{}' or "
     82                                    "higher is required".format(mod.__name__,

/mnt/miniconda/envs/jestr-etl/lib/python3.7/distutils/version.py in __lt__(self, other)
     50 
     51     def __lt__(self, other):
---> 52         c = self._cmp(other)
     53         if c is NotImplemented:
     54             return c

/mnt/miniconda/envs/jestr-etl/lib/python3.7/distutils/version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by martindurant** [comment]
@TomAugspurger  ?

**Comment by TomAugspurger** [comment]
When you `pip install` s3fs what version do you get, and what is `s3fs.__version__`?

```
Successfully installed s3fs-0.3.4+2.g882b7b3
In [2]: s3fs.__version__
Out[2]: '0.3.4+2.g882b7b3'
```

This should have been fixed by https://github.com/dask/s3fs/pull/227

**Comment by birdsarah** [comment]
I'm doing 

```
conda uninstall s3fs --force
pip install https://github.com/dask/s3fs/archive/master.zip
```

The version is something like `0+....` - I don't have it in front of me.

**Comment by TomAugspurger** [comment]
Seems to be an issue with versioner and zip files: https://github.com/warner/python-versioneer/issues/140

It works with `pip install git+https://github.com/dask/s3fs/`

**Comment by birdsarah** [comment]
For others may be using this in the future. The logs are only visible via `yarn logs` after the cluster is closed - they don't show up, for me, in distributed dashboard view of logs.

**Pull request merged**
