### PR TITLE
ENH: add support for requester pays buckets

### PR DESCRIPTION
**Pull request by tacaswell**
Only read-operations are supported

Ran into this trying to access arXiv data (https://arxiv.org/help/bulk_data_s3) for an example of this in the wild.

### CODE REVIEW

**Comment by mrocklin** [comment]
I don't suppose there is a way to mock this out with moto?

**Comment by mrocklin** [comment]
(also awesome, thanks for doing this!)

**Comment by tacaswell** [comment]
`git grep -i payer` on the moto code base does not turn anything up.  

Due to the way RequesterPays works, you _must_ authenticate (so they know who to charge).   To test this you would have to set up moto buckets with interesting ACL, but it seems to not mock those out (tested by setting 'ACL' in the fixture to jibberish or the value of RequestPayer to jibberish and the tests still pass).

**Comment by mrocklin** [comment]
In that case I'm +1 to merge this. 

Merging soon if no further comments.

**Comment by martindurant** [comment]
Thanks for doing this!
Any chance we could have a sentence or two in the docs on when to use this (perhaps with your arxiv example).

**Pull request merged**
