### PR TITLE
Ensure s3fs works with byte arrays

### PR DESCRIPTION
**Pull request by mrocklin**
See https://github.com/alimanfoo/zarr/pull/22

### CODE REVIEW

**Comment by mrocklin** [comment]
@alimanfoo it looks like `array.array` doesn't support the buffer interface in 27.  Thoughts on the best way to handle this?

**Comment by alimanfoo** [comment]
I forgot about that. I have to work around that in Zarr too. I'd suggest adding a check on entry into ``__setitem__``:

```
if PY2 and isinstance(value, array.array):
    value = value.tostring()
```

**Comment by martindurant** [comment]
Looks good to me - all is good on the zarr side?

**Comment by mrocklin** [comment]
I think we're good.  Merging.

**Pull request merged**
