### PR TITLE
autopep8 and pycharm format to improve code style

### PR DESCRIPTION
**Pull request by blackmagic02881**
refactor code with better codestyle.

### CODE REVIEW

**Comment by martindurant** [comment]
Sorry, you now have a conflict, after I merged other PRs.

**Comment by blackmagic02881** [comment]
i resolved the conflict. pls check if could merge. thanks

**Comment by blackmagic02881** [comment]
could someone help to check this? before another conflict shows up. thanks

**Comment by martindurant** [comment]
OK, this is fine. Thank you and pep and pycharm's tools :)

**Pull request merged**
