### PR TITLE
Fix missing type in info() for version-aware buckets

### PR DESCRIPTION
**Pull request by yzq89**
Fixes https://github.com/dask/s3fs/issues/275

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks. Are you able to add a test for this? It may not be possible, if moto doesn't support creating versioned files.

**Comment by yzq89** [comment]
I'm fairly new to tests, hopefully I got it in the right place? pytest showed the expected results.

**Comment by TomAugspurger** [comment]
Thanks, that looks good.

FYI, I edited the text of your GitHub comment to say "Fixes #275" rather than addresses, so that the issue gets auto-closed.

**Comment by martindurant** [comment]
Thank you @yzq89 !

**Comment by yzq89** [comment]
Awesome! Glad to help

**Pull request merged**
