### PR TITLE
Initial fix

### PR DESCRIPTION
**Pull request by drorata**
As discussed on #156, this natural fix breaks the test `test_s3fs.py::test_dynamic_add_rm`.

### CODE REVIEW

**Comment by martindurant** [comment]
The failure appears to be a misalignment of versions of moto and botocore. Perhaps try setting the version of botocore installed in the `.travis.yaml` file to a few versions back? I take ti this passes for you locally, so you might want to use whatever versions of boto3 and botocore you happen to have.

**Comment by drorata** [comment]
Indeed, I was unable to install the dependencies using `test_requirements.txt`. I changed it to:

```
# test_requirements.txt
boto3==1.9.38
botocore>=1.12.13
futures     ; python_version<"3.2"
mock
moto>=1.0
pytest>=2.7.3
```

Regardless (i.e. it is not a versions issue), I get a specific fail for the test I mentioned above.

**Comment by martindurant** [comment]
Can you please push those versions, so that I can see your failure in the CI?
Indeed, it may be better in the future to install from conda rather than pip, in which case there would be a single alternate line in .travis.yaml

**Comment by drorata** [comment]
I have just pushed the dependencies that I ended up with.

**Comment by martindurant** [comment]
Seems to fix:
```
diff --git a/s3fs/core.py b/s3fs/core.py
index dd576e8..deb5d6c 100644
--- a/s3fs/core.py
+++ b/s3fs/core.py
@@ -375,7 +375,7 @@ class S3FileSystem(object):
                 if dirs:
                     files.extend([{'Key': l['Prefix'][:-1], 'Size': 0,
                                   'StorageClass': "DIRECTORY"} for l in dirs])
-                files = [f for f in files if len(f['Key']) > len(prefix)]
+                # files = [f for f in files if len(f['Key']) > len(prefix)]
                 for f in files:
                     f['Key'] = '/'.join([bucket, f['Key']])
             except ClientError as e:
@@ -957,9 +957,7 @@ class S3FileSystem(object):
             raise FileNotFoundError(path)
         if recursive:
             self.invalidate_cache(path)
-            self.bulk_delete(self.walk(path), **kwargs)
-            if not self.exists(path):
-                return
+            self.bulk_delete(self.walk(path, directories=True), **kwargs)
         bucket, key = split_path(path)
         if key:
             try:
```

**Comment by drorata** [comment]
Issue is solved locally! TravisCI still fails.

**Comment by drorata** [comment]
Something is still not working as expected on CI.

**Comment by martindurant** [comment]
Getting there :)
It seems moto isn't good about specifying its requirements

**Comment by martindurant** [comment]
That will have to do.
Thanks, @drorata !

**Pull request merged**
