### PR TITLE
Change glob()'s treatment of dot and slash

### LINKED ISSUE #122: Dots (.) in glob
`glob` doesn't seem to be dealing with dots (`.`) correctly:
```python3
>>> from s3fs import S3FileSystem
>>> s3 = S3FileSystem()
>>> s3.ls("s3fs-glob-test")
['s3fs-glob-test/ab.txt']
>>> s3.glob("s3fs-glob-test/a.*.txt")
['s3fs-glob-test/ab.txt']
```
The path is returned even though `ab.txt` shouldn't match the pattern `a.*.txt`.

### PR DESCRIPTION
**Pull request by zhangwen0411**
Fixes #122.

I also slightly changed how slashes are treated in some places, squashing multiple consecutive slashes into one. Not sure if that's the desired behavior, though.

### CODE REVIEW

**Comment by martindurant** [comment]
Thank you for this, what you've done looks very reasonable - especially as it reuses `fnmatch`'s logic. I would request that, rather than adding more methods onto the S3FileSystem class, the code is either inlined within `glob` or moved as functions within the utils module.
If you are interested, exactly the same code could be ported to gcsfs.

**Comment by zhangwen0411** [comment]
Ah I see! So what's the purpose of replacing `//` with `/` in the original implementation (e.g., https://github.com/dask/s3fs/blob/master/s3fs/core.py#L613)? Should I just leave the slashes alone?

Thanks!

**Comment by martindurant** [comment]
I see what you mean, and honestly I don't know. This may have been copied from hdfs3, which requires posix-compliant paths where such separator mergers happen. Keys can also end with '/' legally, without being directories - so probably best to try dropping the slash handling and see if it breaks any assumptions in the tests.

**Comment by martindurant** [comment]
Thank you!

**Pull request merged**
