### PR TITLE
#139 add region_name to create_bucket

### PR DESCRIPTION
**Pull request by delijati**
#139 add region_name to create_bucket

### CODE REVIEW

**Comment by martindurant** [comment]
I think `region_name=None` should be an optional argument to `mkdir`, and that the fallback default in this code should only be used as the fallback for the `None`. What do you think?

**Comment by delijati** [comment]
Changed it to this comment https://github.com/boto/boto3/issues/781#issuecomment-241916064

**Comment by delijati** [comment]
btw. is it also possible to copy from user a bucket to a user b bucket, with different permissions?

**Comment by martindurant** [comment]
Yep, I like that.
Please also add the parameter to the docstring in `mkdir`. I have no idea why py35, in particular, is failing, but it looks unrelated, perhaps a different version of the boto/moto stack. It would probably be reasonable to not test on py35 any more.

**Comment by martindurant** [comment]
> is it also possible to copy from user a bucket to a user b bucket, with different permissions?

I don't know - I don't see why not.

**Comment by delijati** [comment]
> is it also possible to copy from user a bucket to a user b bucket, with different permissions?
> I don't know - I don't see why not.

it seams only over first copying to local disk :/

https://stackoverflow.com/questions/41939170/copy-ami-from-one-aws-account-to-another-aws-account-using-boto

**Comment by martindurant** [comment]
OK, going to merge this, and should open an issue to look into the py35 failure.

**Pull request merged**
