### PR TITLE
Bugfix/fix tests for windows

### PR DESCRIPTION
**Pull request by anetbnd**
In my preparation for the fix of issue https://github.com/dask/s3fs/issues/422 I first fixed some issues with the test-suite, which I noticed on my windows 10 system. More details are in the comments.

I happy to receive your feedback.

### CODE REVIEW

**Review by martindurant — COMMENTED** [review]
Excellent, thank you!
I have the one query on botocore's version (note that we actually call aiobotocore)

**Comment by anetbnd** [comment]
@martindurant You are welcome. I don't know, if I understand you correctly. You have concerns about the `botocore` request from the `test_requirements.txt`. Do you want to delete it completely or just do you want me to change it to a `aiobotocore` requirement (which might probably also limit the `botocore` version to the right range). Just tell me and I can adapt it.

**Comment by martindurant** [comment]
aoibotocore is already in the requirements, so I don't think you need it here. Did you fail to install/test without it?
Pinning the version so tightly is a separate problem, because we would have to continually update both aoibotocore and botocore versions as new versions come it.

**Comment by martindurant** [comment]
Since aiobotocore is in requirements.txt, I don't think you need it here; in any case, setting a precise pin like that would mean having to constantly update it.

**Comment by martindurant** [comment]
(sorry, system reset meant you got two versions of this comment!)

**Comment by anetbnd** [comment]
@martindurant No problem, I can delete it.

Yes, I had issues when installing the environment. I first installed the `requirements.txt` which lead to the right version of `botocore`. Then I installed the `test-requirements.txt`, which automatically updated the version to the latest one (due to missing restrictions in that file). However the new pip installer is afterwards showing a warning about the incompatible version with already installed packages. 

However it does not lead to any errors in the test-cases, I think it is just a formal error due to too tight version requirements from `aiobotocore` (I have exactly the same option about too tight version requirements like you). 

So I will delete it from the `test-requirements.txt`.

**Comment by martindurant** [comment]
Thanks for this!

**Pull request merged**
