### PR TITLE
Update doc and add kwargs to walk et al

### LINKED ISSUE #207: refresh arg for glob is gone in 0.3
s3fs 0.2.1 has the `refresh` arg for `glob` as introduced with #172 

With the merge of #161 this is now gone in 0.3x again...

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #207

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Test errors are not caused by moto.  Seems to come from master fsspec ?

**Comment by mariusvniekerk** [comment]
Using this environment

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
aws-sam-translator        1.11.0                     py_1    conda-forge
aws-xray-sdk              0.95                       py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1             py37_1000    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.9.194                    py_0    conda-forge
botocore                  1.12.194                   py_0    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cfn-lint                  0.21.2                     py_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cookies                   2.2.1                      py_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
docker-py                 4.0.2                    py37_0    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
docutils                  0.14                  py37_1001    conda-forge
ecdsa                     0.13                       py_0    conda-forge
flask                     1.1.1                      py_0    conda-forge
fsspec                    0.3.4                      py_0    conda-forge
future                    0.17.1                py37_1000    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
importlib_metadata        0.18                     py37_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jsondiff                  1.1.2                      py_0    conda-forge
jsonpatch                 1.23                       py_0    conda-forge
jsonpickle                1.2                        py_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mock                      3.0.5                    py37_0    conda-forge
more-itertools            7.1.0                      py_0    conda-forge
moto                      1.3.12                     py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
py                        1.8.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycryptodome              3.8.2            py37he80fd80_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.1                      py_0    conda-forge
pyrsistent                0.15.3           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
pytest                    5.0.1                    py37_1    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-jose               2.0.2                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py37h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
responses                 0.9.0                      py_0    conda-forge
s3fs                      0.3.1                      py_0    conda-forge
s3transfer                0.2.1                    py37_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
sshpubkeys                3.1.0                      py_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
websocket-client          0.56.0                   py37_0    conda-forge
werkzeug                  0.15.5                     py_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
wrapt                     1.11.2           py37h516909a_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zipp                      0.5.1                      py_0    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge

```

I can successfully run the test suite.  ???

**Comment by mariusvniekerk** [comment]
Okay https://github.com/spulec/moto/commit/e4a4e6183560489e98b95e815b439c7a1cf3566c

**Comment by mariusvniekerk** [comment]
Cutting a new moto conda-forge build with this constrained

**Comment by mariusvniekerk** [comment]
@martindurant I would recommend you explicitly add a more lower bound pin for moto in the travis configuration.  It seems as if the conda solver picked something rather dumb here?

**Comment by mariusvniekerk** [comment]
as in i'd remove botocore and boto3 from the deps.

**Comment by martindurant** [comment]
Got it, thanks @mariusvniekerk

**Pull request merged**
