### PR TITLE
Various small changes

### PR DESCRIPTION
**Pull request by mrocklin**
1.  Create a directory for mapping if it doesn't exist.
2.  Include original exception error messages

### CODE REVIEW

**Comment by martindurant** [comment]
S3 keys don't really need a "directory key" to live within. The empty key wouldn't hurt, I suppose.

**Comment by martindurant** [comment]
The problem is with recursive rm: if there are not actually any files below to pass to bulk_delete.

**Comment by mrocklin** [comment]
I ran into this when creating a mapping from a non-existent bucket, in which case the mkdir does become necessary (I think).

**Comment by martindurant** [comment]
Ah, so it's not the directory you want to create per se, but the bucket for it to live within. I'm not sure we should do that automatically.

**Comment by mrocklin** [comment]
What would you recommend?  Improved error message?

**Comment by martindurant** [comment]
Error message I think, yes. Either happens at check time or on first write when `check=False`.

**Comment by mrocklin** [comment]
Thoughts on adding a `create=False` keyword argument to create the bucket if necessary and having the error message point them towards that keyword argument?  This seems significantly more convenient and helps mapping users (e.g. zarr users) from having to be exposed to the S3FileSystem API.

**Comment by martindurant** [comment]
OK, fine with me. The whole mapping thing of course is for zarr's convenience. Most users of s3fs itself probably won't touch it.

**Pull request merged**
