### PR TITLE
Declare support for Python 3.8

### PR DESCRIPTION
**Pull request by Jamim**
Hello,

Python 3.8 is there, so I believe that it would be nice to declare support and add tests for it on CI.

Python 3.8.0 release announcement:
https://discuss.python.org/t/python-3-8-0-is-now-available/2478

These changes also:
 - make tests use [tox](https://tox.readthedocs.io/en/latest/)
 - enable testing for Python 3.5
 - simplify `.travis.yml`
 - remove redundant `test_requirements.txt`
 - add `.venv/` to `.gitignore`

Best regards!

### CODE REVIEW

**Comment by TomAugspurger** [comment]
We install test dependencies from conda. We’ll probably wait for conda packages and then just add a 3.8 job.

**Comment by Jamim** [comment]
> We install test dependencies from conda.

Is there a reason to use `conda` instead of `pip` (PyPI) on CI?

**Comment by TomAugspurger** [comment]
It's what we use now, and changing things up in the CI is always risky. I'd
prefer to just wait for conda-forge to package 3.8, which should be done in
the next couple days.

**Comment by martindurant** [comment]
(in some cases, it would be reasonable to have CI runs with both conda and pip; I don't think this is one)

**Comment by mrocklin** [comment]
Most of our users use Conda, so we should probably test with conda.

**Comment by Jamim** [comment]
> Most of our users use Conda

It doesn't look so.

[PyPI stats](https://pypistats.org/packages/s3fs):
> Downloads **last month**: 2,414,836

[Conda stats](https://anaconda.org/conda-forge/s3fs):
> 596,802 **total** downloads

**Comment by mrocklin** [comment]
I wonder how that relates to our user survey

**Comment by martindurant** [comment]
Of course, s3fs is not necessarily used with dask; but also, s3fs is included in the Anaconda installer, so we don't know how many people never update. On top of that, some downloads are caused by mirrors, and sometimes installs come from mirrors; plus the environment behaviours of conda and venv users is likely quite different. In short, I'm not sure the comparison above is useful. 

I would not be against testing via pip *in addition* to conda, except if it makes the CI scripts too complex. Conda is the work environment for all of the devs I think.

**Comment by TomAugspurger** [comment]
Fixed in https://github.com/dask/s3fs/pull/264.

Sorry for the lost effort @Jamim! We'll have a release out in a day or two.

**Pull request closed without merging**
