### PR TITLE
Fixing missing boto3 Session.create_client in botocore v. 1.15.39

### PR DESCRIPTION
**Pull request by jesperrix**

### CODE REVIEW

**Comment by jesperrix** [comment]
Sorry, my bad. It looks like if you use 
`session = botocore.session.Session(profile='some-profile')
session.create_client  # exists
`

However when using boto3:
`session = boto3.Session(profile='some-profile')
session.create_client  # Does not exist
# but so does
session.client
`

**Comment by jesperrix** [comment]
And i use s3fs by:
```
session = boto3.Session(profile='some-profile')
fs = s3fs.S3FileSystem(session=session)

**Comment by martindurant** [comment]
Yes, sorry, you should now use a botocore session not a boto3 one. They ought to have the same methods, but they do not. This was done to support async via aiobotocore, but there is no async wrapper for boto3.

**Comment by martindurant** [comment]
I think this will become obsolete following the switch to aiobotocore in #336

**Pull request closed without merging**
